import { AirPods, Box, Package, Phone } from '.'
describe('Composite Problem', () => {
  it('Should be create pagacke', () => {
    const product = new AirPods('Product 1', 10)
    const product2 = new Phone('Product 2', 20)
    const product3 = new Phone('Product 3', 15)
    const pack = new Package()
    pack.addProduct(product)
    pack.addProduct(product2)
    pack.addProduct(product3)
    const price = pack.getPrice()
    expect(price).toBe(45)
  })
  it('Should be create pagacke with box', () => {
    const product = new AirPods('Product 1', 10)
    const product2 = new Phone('Product 2', 20)
    const product3 = new Phone('Product 3', 15)
    const box = new Box()
    box.addProduct(product)
    box.addProduct(product2)
    box.addProduct(product3)
    const pack = new Package()
    pack.addProduct(box)
    const price = pack.getPrice()
    expect(price).toBe(50)
  })
  it('Should be create pagacke with box and product', () => {
    const product = new AirPods('Product 1', 10)
    const product2 = new Phone('Product 2', 30)
    const product3 = new Phone('Product 3', 25)
    const box = new Box()
    box.addProduct(product)
    box.addProduct(product2)
    const pack = new Package()
    pack.addProduct(box)
    pack.addProduct(product3)
    const price = pack.getPrice()
    expect(price).toBe(70)
  })
  it('Should be create pagacke with box mutliple boxes', () => {
    const product = new AirPods('Product 1', 10)
    const product2 = new Phone('Product 2', 30)
    const product3 = new Phone('Product 3', 25)
    const box = new Box()
    box.addProduct(product)
    box.addProduct(product2)
    const box2 = new Box()
    box2.addProduct(product3)
    const pack = new Package()
    pack.addProduct(box)
    pack.addProduct(box2)
    const price = pack.getPrice()
    expect(price).toBe(75)
  })
})
