import { CarBuilder, Director, ManualBuilder } from './index'
import { testTesla, testCustom, testRacing, testSUV, testTruck } from 'builder'

describe('Builder Solution', () => {
  it('client should be create a Tesla car and manual', () => {
    const director = new Director()
    const carBuilder = new CarBuilder()
    director.createTesla(carBuilder)
    const teslaCar = carBuilder.getResult()
    const manualBuilder = new ManualBuilder()
    director.createTesla(manualBuilder)
    const teslaManual = manualBuilder.getResult()
    expect(teslaCar).toEqual(testTesla.car)
    expect(teslaManual).toEqual(testTesla.manual)
  })
  it('client should be create a SUV car and manual', () => {
    const director = new Director()
    const carBuilder = new CarBuilder()
    director.createSUV(carBuilder)
    const suvCar = carBuilder.getResult()
    const manualBuilder = new ManualBuilder()
    director.createSUV(manualBuilder)
    const suvManual = manualBuilder.getResult()
    expect(suvCar).toEqual(testSUV.car)
    expect(suvManual).toEqual(testSUV.manual)
  })
  it('client should be create a Truck car and manual', () => {
    const director = new Director()
    const carBuilder = new CarBuilder()
    director.createTruck(carBuilder)
    const truckCar = carBuilder.getResult()
    const manualBuilder = new ManualBuilder()
    director.createTruck(manualBuilder)
    const truckManual = manualBuilder.getResult()
    expect(truckCar).toEqual(testTruck.car)
    expect(truckManual).toEqual(testTruck.manual)
  })
  it('client should be create a Racing car and manual', () => {
    const director = new Director()
    const carBuilder = new CarBuilder()
    director.createRacing(carBuilder)
    const racingCar = carBuilder.getResult()
    const manualBuilder = new ManualBuilder()
    director.createRacing(manualBuilder)
    const racingManual = manualBuilder.getResult()
    expect(racingCar).toEqual(testRacing.car)
    expect(racingManual).toEqual(testRacing.manual)
  })
  it('client should be create a Custom car and manual', () => {
    const carBuilder = new CarBuilder()
    carBuilder.setColor('yellow')
    carBuilder.setDoors(2)
    carBuilder.setEngine('gasoline v8')
    carBuilder.setExtra(['airbag', 'aircondition', 'aileron', 'polarized glasses'])
    carBuilder.setGPS(true)
    carBuilder.setAutoPilot(true)
    carBuilder.setSeats(2)
    const customCar = carBuilder.getResult()
    const manualBuilder = new ManualBuilder()
    manualBuilder.setDoors(2)
    manualBuilder.setEngine('gasoline v8')
    manualBuilder.setExtra(['airbag', 'aircondition', 'aileron', 'polarized glasses'])
    manualBuilder.setGPS(true)
    manualBuilder.setAutoPilot(true)
    manualBuilder.setSeats(2)
    manualBuilder.setColor('yellow')

    const customManual = manualBuilder.getResult()
    expect(customCar).toEqual(testCustom.car)
    expect(customManual).toEqual(testCustom.manual)
  })
})
